- hosts: manager
  name: Creating CEPH cluster directory
  become: yes
  become_user: cephadm
  tasks:
   - file:
      path: /home/cephadm/cluster
      state: directory     
      mode: 0755

- hosts: manager
  name: Installing ceph-deploy
  tasks:
   - apt: name=ceph-deploy default_release=jessie-backports

- hosts: all
  name: Installing ceph-deploy
  tasks:
   - apt: name=radosgw default_release=jessie-backports

- hosts: manager
  name: Installing CEPH cluster
  become: yes
  become_user: cephadm
  tasks:
   - shell: ceph-deploy --overwrite-conf new manager
     args: 
      chdir: /home/cephadm/cluster   

- hosts: manager
  name: Deploy Ceph-cluster in all nodes
  become: yes
  become_user: cephadm
  tasks:
   - shell: ceph-deploy --overwrite-conf install manager node1 node2
     args:
      chdir: /home/cephadm/cluster
      warn: yes

- hosts: manager
  name: Deploy2 Ceph-cluster in all nodes
  become: yes
  become_user: cephadm
  tasks:
   - shell: ceph-deploy mon create-initial
     args:
      chdir: /home/cephadm/cluster

- hosts: manager
  name: Add disks to cluster
  become: yes
  become_user: cephadm
  tasks:
   - shell: ceph-deploy disk zap {{ item }} sdb
     args:
      chdir: /home/cephadm/cluster
     with_items:
      - manager
      - node1
      - node2

- hosts: manager
  name: Add disks to cluster 2
  become: yes
  become_user: cephadm
  tasks:
   - shell: ceph-deploy --overwrite-conf osd prepare {{ item }} sdb 
     args:
      chdir: /home/cephadm/cluster
     with_items:
      - manager
      - node1
      - node2

- hosts: manager
  name: Add disks to cluster 3
  become: yes
  become_user: cephadm
  tasks:
   - shell: ceph-deploy osd activate {{ item }} sdb1 
     args:
      chdir: /home/cephadm/cluster
     with_items:
      - manager
      - node1
      - node2

- hosts: all
  name: Copy conf files to nodes
  become: yes
  become_user: cephadm
  tasks:
    - shell: ceph-deploy admin manager node1 node2
      args:
       chdir: /home/cephadm/cluster
- hosts: all
  name: Give read permissions to nodes
  tasks:
   - file: 
      src: /etc/ceph/ceph.client.admin.keyring
      mode: "u+r,g+r,o+r"

- hosts: manager
  name: Install Metadata Server for FS
  become: yes
  become_user: cephadm
  tasks: 
   - shell: ceph-deploy mds create cephadm
     args:
      chdir: /home/cephadm/cluster

- hosts: manager
  name: Install Rados Gateway for Object Gateway
  become: yes
  become_user: cephadm
  tasks:
   - shell: ceph-deploy rgw create cehpadm
     args:
      chdir: /home/cephadm/cluster

- hosts: all
  name: Create fstab entry for automount
  tasks:
   - shell: "RES=`mount | grep osd | awk '{print $3}'`"
     register: RES
   - shell: echo /dev/sdb1 $RES  xfs rw,noatime,attr2,inode64,noquota        0


