- name: Installing CEPH cluster
  hosts: manager
  tasks:
   file:
    path: /home/cephadm/cluster
    state: directory     
    command: chdir=/home/cephadm/cluster ceph-deploy new cephadm
   become: yes
   become_user: cephadm

- name: Deploy Ceph-cluster in all nodes
  hosts: manager
  tasks:
   command: ceph-deploy install manager node1 node2
   command: ceph-deploy mon create-initial
   become: yes
   become_user: cephadm

- name: Add disks to cluster
  hosts: manager
  tasks:
   command: ceph-deploy disk zap "{{item}}":sdb
   become: yes
   become_user: cephadm
   with_items:
    - manager
    - node1
    - node2

- name: Add disks to cluster
  hosts: manager
  tasks:
   command: ceph-deploy --overwrite-conf osd prepare "{{item}}":sdb 
   become: yes
   become_user: cephadm
   with_items:
    - manager
    - node1
    - node2

- name: Add disks to cluster
  hosts: manager
  tasks:
   command: ceph-deploy osd activate "{{item}}":sdb1 
   become: yes
   become_user: cephadm
   with_items:
    - manager
    - node1
    - node2

- name: Copy conf files to nodes
  hosts: all
  tasks:
   command: ceph-deploy admin manager node1 node2
   become: yes
   become_user: cephadm

- name: Give read permissions to nodes
  hosts: all
  tasks:
   file: 
    src: /etc/ceph/ceph.client.admin.keyring
    mode: "u+r,g+r,o+r"

- name: Install Metadata Server for FS
  hosts: manager
  tasks: 
   command: ceph-deploy mds create cephadm
   become: yes
   become_user: cephadm

- name: Install Rados Gateway for Object Gateway
  hosts: manager
  tasks:
   command: ceph-deploy rgw create cehpadm
   become: yes
   become_user: cephadm

- name: Create fstab entry for automount
  hosts: all
  tasks:
   command: RES=`mount | grep osd | awk '{print $3}'`; echo "/dev/sdb1 $RES  xfs rw,noatime,attr2,inode64,noquota        0 



