- name: Installing CEPH in Manager
  hosts: all
  tasks:
   apt: name=ceph state=present

- name: Install chrony in Cluster
  hosts: all
  tasks:
   apt: name=chrony state=present

- name: Execute sinchrony in Cluster
  hosts: all
  tasks:
   command: rpl "allow 1" "#allow 1" /etc/chrony/chrony.conf

- name: Create cephadm user
  hosts: all
  tasks:
   user:
    name: cephadm
    password: '$6$rGfOATGJ.$K4i0tbpvD9/.HM.HzHcEri/./yPPJkIXypYicWtM.Z9jZNgQkNjDZkuVf/oLtaGta3oiJRJVsSip1n4DkDr560'
    groups:
     - sudo
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/cephadm
   lineinfile:
    dest: /etc/sudoers
    state: present
    regex: '^%cephadm'
    line: '%cephadm ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: cephadm
  hosts: manager
  tasks:
   user:
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Copy SSH key to nodes
  hosts: all
  tasks:
   ssh_copy_id:
    hostname: "{{item}}"
    username: cephadm
    password: changeme
    ssh_public_key: "/home/cephadm/.ssh/id_rsa.pub"
   with_items:
    - manager
    - node1
    - node2

- name: Add cephadm as default ssh user
  hosts: manager
  tasks:
   blockinfile:
    path: /home/cephadm/.ssh/config
    content: |
     Host {{item}}
     Hostname {{item}}
     User cephadm
   with_items:
    - manager
    - node1
    - node2
